//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog
    {
        public int id { get; set; }
        public string blog_name { get; set; }
        public int blog_author { get; set; }
        public string blog_tags { get; set; }
        public string blog_text { get; set; }
        public System.DateTime blog_date { get; set; }
        public string blog_img { get; set; }
        public int blog_category { get; set; }
    
        public virtual author author { get; set; }
        public virtual category category { get; set; }
    }
}
