//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.blogs = new HashSet<blog>();
            this.news = new HashSet<news>();
        }
    
        public int id { get; set; }
        public string category_name { get; set; }
    
        public virtual ICollection<blog> blogs { get; set; }
        public virtual ICollection<news> news { get; set; }
    }
}
