//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.departDoctors = new HashSet<departDoctor>();
            this.worktimes = new HashSet<worktime>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string speciality { get; set; }
        public int gender { get; set; }
        public string facebook_adress { get; set; }
        public string twitter_adress { get; set; }
        public string google_adress { get; set; }
        public string image { get; set; }
    
        public virtual ICollection<departDoctor> departDoctors { get; set; }
        public virtual ICollection<worktime> worktimes { get; set; }
    }
}
