//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public int id { get; set; }
        public string news_name { get; set; }
        public int news_author { get; set; }
        public string news_text { get; set; }
        public string news_img { get; set; }
        public System.DateTime news_date { get; set; }
        public int news_category { get; set; }
    
        public virtual author author { get; set; }
        public virtual category category { get; set; }
    }
}
